name: Build Rust and NPM Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Change directory to web
        run: cd web

      - name: Install NPM dependencies
        run: |
            cd web
            npm ci

      - name: Build NPM project
        run: |
            cd web
            npx tsc

      - name: Build Rust project
        run: STATIC_ASSETS=1 cargo build --release

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build artifacts
          path: ./target/release/aki
